// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5L8tUxJ3wgT4FS2Sc5rQBp5NN6AVdKHE',
    appId: '1:672765729577:web:868a8ae551057e5c52b538',
    messagingSenderId: '672765729577',
    projectId: 'fir-demo-26921',
    authDomain: 'fir-demo-26921.firebaseapp.com',
    storageBucket: 'fir-demo-26921.firebasestorage.app',
    measurementId: 'G-8TPGW2NVJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_gV8WE5pqEDooAtJe9lM-s7fpc836sVo',
    appId: '1:672765729577:android:6a3387463e51208f52b538',
    messagingSenderId: '672765729577',
    projectId: 'fir-demo-26921',
    storageBucket: 'fir-demo-26921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJ9aIoRe5b2eMyoS8DTFqqwOvSjuaOl4',
    appId: '1:672765729577:ios:200b7925207cacdf52b538',
    messagingSenderId: '672765729577',
    projectId: 'fir-demo-26921',
    storageBucket: 'fir-demo-26921.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChJ9aIoRe5b2eMyoS8DTFqqwOvSjuaOl4',
    appId: '1:672765729577:ios:200b7925207cacdf52b538',
    messagingSenderId: '672765729577',
    projectId: 'fir-demo-26921',
    storageBucket: 'fir-demo-26921.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5L8tUxJ3wgT4FS2Sc5rQBp5NN6AVdKHE',
    appId: '1:672765729577:web:2621f3ef3fea8f6d52b538',
    messagingSenderId: '672765729577',
    projectId: 'fir-demo-26921',
    authDomain: 'fir-demo-26921.firebaseapp.com',
    storageBucket: 'fir-demo-26921.firebasestorage.app',
    measurementId: 'G-ZEGSGVNFRV',
  );
}
